### ISSUE TITLE
Protection DDOS cote serveur (requête http page accueil vulnérable)

### ISSUE THREAD

**Issue by Grivel-l** [julien-marquet/101_MAP#29]
Ouah j'ai peiné à comprendre `DeadOS`. C'est `DDOS`. En quoi on est vulnérable ?

**Comment by AlexisVisco** [comment]
Je passe en coup de vent au cas où vous pourriez essayer ça: https://nodejs.org/api/cluster.html

**Comment by Grivel-l** [comment]
Je connaissais pas ça à l'air pas mal :+1: Mais cet issue est plus trop d'actualité, on a un système de cache et de queue qui handle maximum 4 requests par secondes (notre limite sur l'api)
