### ISSUE TITLE
Plantage Ecran Accueil

### ISSUE THREAD

**Issue by julien-marquet** [julien-marquet/101_MAP#68]
https://drive.google.com/file/d/1FFlLq8mu2UaBep4ja0nyuAOPy64kFNVZ/view?usp=sharing

**Comment by Grivel-l** [comment]
![image](https://user-images.githubusercontent.com/20241441/49460355-66486680-f7f1-11e8-9e26-65fd0ff93abe.png)

**Comment by Grivel-l** [comment]
3bb895ef595eed9470382273520509ddf496f8ee

**Comment by Grivel-l** [comment]
Ici plutot a12c98f4a896e06fad9045d7770374c518abda34

**Comment by Grivel-l** [comment]
Definitivement ici 364f72e9105a78ab5cbba55e9a4bda812a4c4afc
